using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace OllamaPilot
{
    /// <summary>
    /// Represents the request options for a text generation task.
    /// </summary>
    public sealed class RequestOptions
    {
        /// <summary>
        /// The number of context tokens to use in the model's response. This can be used for generating summaries or paraphrases.
        /// </summary>
        public int? NumCtx { get; set; }

        /// <summary>
        /// The number of predictions to generate from the model. This can be used for generating multiple completions or alternative answers.
        /// </summary>
        public int? NumPredict { get; set; }

        /// <summary>
        /// The temperature parameter controls the randomness of the generated text. Higher values make the output more random, while lower values make it more deterministic and predictable.
        /// </summary>
        public float? Temperature { get; set; }

        /// <summary>
        /// An array of stop tokens that can be used to control the generation process. The model will stop generating when it encounters one of these tokens in the input or output text.
        /// </summary>
        public string[] Stop { get; set; }
    }

    /// <summary>
    /// Represents a request to generate a completion text using the specified model and prompt.
    /// </summary>
    public class GenerateCompletionRequest
    {
        /// <summary>
        /// The name of the language model used for generating the completion. This can be one of several popular models such as GPT-4, BERT, or T5.
        /// </summary>
        public string Model { get; set; }

        /// <summary>
        /// The input prompt that will be used to generate the completion text. This is the core of the request and should contain the context for generating the output.
        /// </summary>
        public string Prompt { get; set; }

        /// <summary>
        /// An optional suffix that can be added to the generated completion text. This can be useful for adding additional information or formatting the output in a specific way.
        /// </summary>
        public string Suffix { get; set; }

        /// <summary>
        /// The request options for generating the completion. These options control various aspects of the generation process such as temperature, number of context tokens, and stop tokens.
        /// </summary>
        public RequestOptions Options { get; set; }

        /// <summary>
        /// A boolean flag indicating whether the raw response from the model should be returned instead of processed output text. This can be useful for debugging or accessing the underlying model outputs directly.
        /// </summary>
        public bool Raw { get; set; }
    }

    /// <summary>
    /// Represents the result of a text generation task.
    /// </summary>
    public sealed class GenerateCompletionResult
    {
        /// <summary>
        /// The completion text generated by the model. This is the output of the request and contains the generated response to the input prompt.
        /// </summary>
        public string Response { get; set; }
    }

    /// <summary>
    /// Represents a model used for text generation tasks.
    /// </summary>
    public sealed class Model
    {
        /// <summary>
        /// The name of the model, which uniquely identifies it among other models. This can be one of several popular models such as GPT-4, BERT, or T5.
        /// </summary>
        public string Name { get; set; }
    }

    /// <summary>
    /// Represents the response from a model when the user requests to show its parameters and template.
    /// </summary>
    public sealed class ShowModelResponse
    {
        /// <summary>
        /// A JSON string containing the parameters of the model. These parameters are typically used for configuring the model's behavior, such as temperature or number of context tokens.
        /// </summary>
        public string Parameters { get; set; }

        /// <summary>
        /// A template string that can be used to format the output of the model's responses. This template is often used for generating human-like text in natural language.
        /// </summary>
        public string Template { get; set; }
    }

    /// <summary>
    /// Represents a chat response stream from the model during a conversation.
    /// </summary>
    public sealed class ChatResponseStream
    {
        /// <summary>
        /// The name of the model used for generating the responses. This can be one of several popular models such as GPT-4, BERT, or T5.
        /// </summary>
        public string Model { get; set; }

        /// <summary>
        /// The current message being processed in the conversation. This contains the user's input and the model's response to that input.
        /// </summary>
        public Message Message { get; set; }

        /// <summary>
        /// A boolean flag indicating whether the stream has finished processing all messages and is ready for further operations. When this flag is true, the stream can be used for generating text or performing other operations.
        /// </summary>
        public bool Done { get; set; }
    }

    /// <summary>
    /// Represents a chat message that can be sent between the model and the user.
    /// </summary>
    public sealed class Message
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Message"/> class with the specified role, content, and images.
        /// </summary>
        public Message(ChatRole role, string content, string[] images)
        {
            Role = role;
            Content = content;
            Images = images;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Message"/> class with the specified role and content.
        /// </summary>
        public Message(ChatRole role, string content)
        {
            Role = role;
            Content = content;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Message"/> class without any parameters.
        /// </summary>
        public Message()
        {
        }

        /// <summary>
        /// The role of the message. This can be one of several predefined roles such as "user", "assistant", or "system".
        /// </summary>
        public ChatRole? Role { get; set; }

        /// <summary>
        /// The content of the message, which could be text or an image URL.
        /// </summary>
        public string Content { get; set; }

        /// <summary>
        /// Optional thinking text emitted by reasoning-capable models.
        /// </summary>
        public string Thinking { get; set; }

        /// <summary>
        /// An array of images associated with the message. This can be used for visual prompts in language generation tasks.
        /// </summary>
        public string[] Images { get; set; }
    }

    public readonly struct ChatRole : IEquatable<ChatRole>
    {
        private const string AssistantValue = "assistant";
        private const string SystemValue = "system";
        private const string UserValue = "user";
        private readonly string _value;

        public ChatRole(string role)
        {
            _value = role ?? throw new ArgumentNullException(nameof(role));
        }

        public static ChatRole System { get; } = new ChatRole(SystemValue);
        public static ChatRole Assistant { get; } = new ChatRole(AssistantValue);
        public static ChatRole User { get; } = new ChatRole(UserValue);

        public static bool operator ==(ChatRole left, ChatRole right)
        {
            return left.Equals(right);
        }

        public static bool operator !=(ChatRole left, ChatRole right)
        {
            return !left.Equals(right);
        }

        public static implicit operator ChatRole(string value)
        {
            return new ChatRole(value);
        }

        public override bool Equals(object obj)
        {
            return obj is ChatRole other && Equals(other);
        }

        public bool Equals(ChatRole other)
        {
            return string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);
        }

        public override int GetHashCode()
        {
            return StringComparer.InvariantCultureIgnoreCase.GetHashCode(_value ?? string.Empty);
        }

        public override string ToString()
        {
            return _value ?? string.Empty;
        }
    }

    /// <summary>
    /// Represents a service for interacting with an OpenAI-based language model using the LLama library.
    /// </summary>
    public interface IOllamaService
    {
        /// <summary>
        /// Creates a chat session with the specified settings and starts streaming the responses asynchronously.
        /// </summary>
        /// <param name="baseUrl">The base URL of the OpenAI API.</param>
        /// <param name="model">The model to use for generating the text.</param>
        /// <param name="accessToken">The access token required for authentication with the OpenAI API.</param>
        /// <param name="options">The request options for generating responses during the chat session.</param>
        /// <param name="streamer">An action delegate that will be called to handle each chat response as it is received.</param>
        /// <returns>A task representing the asynchronous operation that completes when the chat session is created and started streaming.</returns>
        Chat CreateChatSession(string baseUrl, string model, string accessToken, RequestOptions options, ThinkingDepth thinkingDepth, Action<ChatResponseStream> streamer);

        /// <summary>
        /// Lists all local models available on the system.
        /// </summary>
        /// <param name="baseUrl">The base URL of the OpenAI API.</param>
        /// <param name="accessToken">The access token required for authentication with the OpenAI API.</param>
        /// <param name="cancellationToken">A cancellation token that can be used to cancel the asynchronous operation.</param>
        /// <returns>A task representing the asynchronous operation that completes when all local models are listed.</returns>
        Task<IReadOnlyList<Model>> ListLocalModelsAsync(string baseUrl, string accessToken, CancellationToken cancellationToken);

        /// <summary>
        /// Retrieves information about a specific model.
        /// </summary>
        /// <param name="baseUrl">The base URL of the OpenAI API.</param>
        /// <param name="accessToken">The access token required for authentication with the OpenAI API.</param>
        /// <param name="model">The name of the model to retrieve information about.</param>
        /// <param name="cancellationToken">A cancellation token that can be used to cancel the asynchronous operation.</param>
        /// <returns>A task representing the asynchronous operation that completes when the model information is retrieved.</returns>
        Task<ShowModelResponse> ShowModelInformationAsync(string baseUrl, string accessToken, string model, CancellationToken cancellationToken);

        /// <summary>
        /// Generates a completion text using the specified request and starts streaming the responses asynchronously.
        /// </summary>
        /// <param name="baseUrl">The base URL of the OpenAI API.</param>
        /// <param name="accessToken">The access token required for authentication with the OpenAI API.</param>
        /// <param name="request">The request options for generating responses during the chat session.</param>
        /// <param name="cancellationToken">A cancellation token that can be used to cancel the asynchronous operation.</param>
        /// <returns>A task representing the asynchronous operation that completes when the completion text is generated and streamed.</returns>
        Task<GenerateCompletionResult> GenerateCompletionAsync(string baseUrl, string accessToken, GenerateCompletionRequest request, CancellationToken cancellationToken);
    }

    public sealed class Chat
    {
        private readonly IChatSession _session;

        internal Chat(IChatSession session)
        {
            _session = session;
        }

        public string SelectedModel
        {
            get { return _session.SelectedModel; }
            set { _session.SelectedModel = value; }
        }

        public RequestOptions Options
        {
            get { return _session.Options; }
            set { _session.Options = value; }
        }

        public string AccessToken
        {
            get { return _session.AccessToken; }
            set { _session.AccessToken = value; }
        }

        public Task SendAsync(string message, CancellationToken cancellationToken)
        {
            return _session.SendAsync(message, cancellationToken);
        }
    }

    /// <summary>
    /// Represents a chat session with the model. This interface provides methods for sending messages to the model and receiving responses.
    /// </summary>
    internal interface IChatSession
    {
        /// <summary>
        /// The name of the selected model being used in the session. This can be one of several popular models such as GPT-4, BERT, or T5.
        /// </summary>
        string SelectedModel { get; set; }

        /// <summary>
        /// The request options for generating responses during the chat session. These options control various aspects of the generation process such as temperature, number of context tokens, and stop tokens.
        /// </summary>
        RequestOptions Options { get; set; }

        /// <summary>
        /// The access token used to authenticate with the model's API. This is typically required for accessing the model's endpoints that require authentication.
        /// </summary>
        string AccessToken { get; set; }

        /// <summary>
        /// Asynchronously sends a message to the model and receives the response asynchronously.
        /// </summary>
        /// <param name="message">The message to send to the model.</param>
        /// <param name="cancellationToken">A cancellation token that can be used to cancel the asynchronous operation.</param>
        /// <returns>A task representing the asynchronous operation that completes when the response is received.</returns>
        Task SendAsync(string message, CancellationToken cancellationToken);
    }
}
